
package com.ibk.proyecto.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */


@WebService(name = "faxSoap", targetNamespace = "http://www.webserviceX.NET")
@XmlSeeAlso({
    ObjectFactory.class
})


public interface FaxSoap {

    /**
     * Send FAX (for free) to any part of the world<br> <span><br><br>This webservice provide a facilty to send fax anywhere in the world.Please add country code (without preceding zero(s)) to your fax number(Without hyphen).<br><I><b>e.g If your number is 0091-435-416353 ,please enter fax number as 91435416353</b></i>	</span><br><b>Please Note:</b><br>The character '_' is converted to a space and The character '/' is converted to start a new line <br>Coverage List :<a href='CheckCoverage.htm'>View</a> 
     * 
     * @param bodyText
     * @param toName
     * @param subject
     * @param faxNumber
     * @param fromEmail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendTextToFax", action = "http://www.webserviceX.NET/SendTextToFax")
    @WebResult(name = "SendTextToFaxResult", targetNamespace = "http://www.webserviceX.NET")
    @RequestWrapper(localName = "SendTextToFax", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.SendTextToFax")
    @ResponseWrapper(localName = "SendTextToFaxResponse", targetNamespace = "http://www.webserviceX.NET", className = "net.webservicex.SendTextToFaxResponse")
    public String sendTextToFax(
        @WebParam(name = "FromEmail", targetNamespace = "http://www.webserviceX.NET")
        String fromEmail,
        @WebParam(name = "Subject", targetNamespace = "http://www.webserviceX.NET")
        String subject,
        @WebParam(name = "FaxNumber", targetNamespace = "http://www.webserviceX.NET")
        String faxNumber,
        @WebParam(name = "BodyText", targetNamespace = "http://www.webserviceX.NET")
        String bodyText,
        @WebParam(name = "ToName", targetNamespace = "http://www.webserviceX.NET")
        String toName);

}
